# Generated by Django 4.0.7 on 2022-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
